const ALERT_TYPES = {
  EXPIRING_16_30_DAYS: "EXPIRING_16_30_DAYS",
  EXPIRING_31_60_DAYS: "EXPIRING_31_60_DAYS",
  EXPIRING_SOON: "EXPIRING_SOON",
  EXPIRED: "EXPIRED",
  LOW_STOCK: "LOW_STOCK",
  OUT_OF_STOCK: "OUT_OF_STOCK",
};

const ALERT_SEVERITIES = {
  HIGH: "HIGH",
  MEDIUM: "MEDIUM",
  LOW: "LOW",
};

module.exports = {
  ALERT_TYPES,
  ALERT_SEVERITIES,
};
